services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/backend/user/User.Api/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  mongoserver:
    image: mongo

networks:
  backend:

volumes:
  sqlserver_data:
  mongoserver_data:  