services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/backend/user/User.Api/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  course.api:
    image: ${DOCKER_REGISTRY-}courseapi
    build:
      context: .
      dockerfile: src/backend/course/Course.Api/Dockerfile

  mongoserver:
    image: mongo
   
  rabbitmq:
    image: rabbitmq:3-management

  redisserver:
    image: redis:latest

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: src/backend/payment/Payment.Api/Dockerfile

  progress.api:
    image: ${DOCKER_REGISTRY-}progressapi
    build:
      context: .
      dockerfile: src/backend/progress/Progress.Api/Dockerfile

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
  mongoserver_data:
  redisserver_data:



