services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/backend/user/User.Api/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  course.api:
    image: ${DOCKER_REGISTRY-}courseapi
    build:
      context: .
      dockerfile: src/backend/course/Course.Api/Dockerfile

  mongoserver:
    image: mongo

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
  mongoserver_data:  
>>>>>>> c9189aac77e3ba53d65bb367efd127c09908893e
