//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payment.Domain.Exceptions.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User balance doesn&apos;t exists.
        /// </summary>
        public static string BALANCE_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("BALANCE_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User balance not exists, or a transaction modified the balance now, try again.
        /// </summary>
        public static string BALANCE_NOT_EXISTS_OR_TRANSACTION_PENDING {
            get {
                return ResourceManager.GetString("BALANCE_NOT_EXISTS_OR_TRANSACTION_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course not found.
        /// </summary>
        public static string COURSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("COURSE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf format is not valid.
        /// </summary>
        public static string CPF_FORMAT_NOT_VALID {
            get {
                return ResourceManager.GetString("CPF_FORMAT_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current currency is not allowed to this method.
        /// </summary>
        public static string CURRENCY_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("CURRENCY_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email format is invalid.
        /// </summary>
        public static string EMAIL_FORMAT_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_FORMAT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value to cashout cannot be greather than balance amount.
        /// </summary>
        public static string INVALID_AMOUNT_IN_BALANCE {
            get {
                return ResourceManager.GetString("INVALID_AMOUNT_IN_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a First name length must be equal or less than 40.
        /// </summary>
        public static string INVALID_FIRST_NAME {
            get {
                return ResourceManager.GetString("INVALID_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Last name length must be equal or less than 60.
        /// </summary>
        public static string LAST_NAME_INVALID {
            get {
                return ResourceManager.GetString("LAST_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User still doesn&apos;t have a order.
        /// </summary>
        public static string ORDER_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("ORDER_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course is already on user order.
        /// </summary>
        public static string ORDER_ITEM_EXISTS {
            get {
                return ResourceManager.GetString("ORDER_ITEM_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Orders don&apos;t exists.
        /// </summary>
        public static string ORDERS_DONT_EXISTS {
            get {
                return ResourceManager.GetString("ORDERS_DONT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment canceled verify the payment infos or try again later.
        /// </summary>
        public static string PAYMENT_CANCELED {
            get {
                return ResourceManager.GetString("PAYMENT_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payout failed, try again later.
        /// </summary>
        public static string PAYOUT_FAILED {
            get {
                return ResourceManager.GetString("PAYOUT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payout pending or made a few times, wait one day for request again.
        /// </summary>
        public static string PAYOUT_MADE_FEW_TIMES_AGO {
            get {
                return ResourceManager.GetString("PAYOUT_MADE_FEW_TIMES_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User bank account is invalid or doesn&apos;t exists.
        /// </summary>
        public static string USER_BANK_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_BANK_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doesn&apos;t have this course.
        /// </summary>
        public static string USER_DOESNT_HAVE_THE_COURSE {
            get {
                return ResourceManager.GetString("USER_DOESNT_HAVE_THE_COURSE", resourceCulture);
            }
        }
    }
}
