//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Course.Exception.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course description length must be less or equal 3000.
        /// </summary>
        public static string COURSE_DESCRIPTION_3000_LENGTH {
            get {
                return ResourceManager.GetString("COURSE_DESCRIPTION_3000_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course doesn&apos;t exists.
        /// </summary>
        public static string COURSE_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("COURSE_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course already is in wish list.
        /// </summary>
        public static string COURSE_IN_WISH_LIST {
            get {
                return ResourceManager.GetString("COURSE_IN_WISH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course language must be within enum.
        /// </summary>
        public static string COURSE_LANGUAGE_OUT_ENUM {
            get {
                return ResourceManager.GetString("COURSE_LANGUAGE_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course is not in wish list.
        /// </summary>
        public static string COURSE_NOT_IN_WISH_LIST {
            get {
                return ResourceManager.GetString("COURSE_NOT_IN_WISH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The course must be of user.
        /// </summary>
        public static string COURSE_NOT_OF_USER {
            get {
                return ResourceManager.GetString("COURSE_NOT_OF_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course or module ids doesn&apos;t exists.
        /// </summary>
        public static string COURSE_OR_MODULE {
            get {
                return ResourceManager.GetString("COURSE_OR_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course description length must be less or equal 256.
        /// </summary>
        public static string COURSE_TITLE_LENGTH_LESS_THAN_256 {
            get {
                return ResourceManager.GetString("COURSE_TITLE_LENGTH_LESS_THAN_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid image name.
        /// </summary>
        public static string INAVLID_IMAGE_NAME {
            get {
                return ResourceManager.GetString("INAVLID_IMAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid course container.
        /// </summary>
        public static string INVALID_COURSE_CONTAINER {
            get {
                return ResourceManager.GetString("INVALID_COURSE_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only format image is png and jpg.
        /// </summary>
        public static string INVALID_FORMAT_IMAGE {
            get {
                return ResourceManager.GetString("INVALID_FORMAT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id format is wrong.
        /// </summary>
        public static string INVALID_ID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_ID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File is not a video or an invalid format.
        /// </summary>
        public static string INVALID_VIDEO_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_VIDEO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lesson doesn&apos;t exists.
        /// </summary>
        public static string LESSON_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("LESSON_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lesson position out of range.
        /// </summary>
        public static string LESSON_POSITION_OUT_RANGE {
            get {
                return ResourceManager.GetString("LESSON_POSITION_OUT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doesn&apos;t have permission for get lesson.
        /// </summary>
        public static string LESSON_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("LESSON_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module description length must be less or equal 600.
        /// </summary>
        public static string MODULE_DESCRIPTION_LENGTH {
            get {
                return ResourceManager.GetString("MODULE_DESCRIPTION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module doesn&apos;t exists.
        /// </summary>
        public static string MODULE_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("MODULE_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module name must be less or equal 100.
        /// </summary>
        public static string MODULE_NAME_LENGTH {
            get {
                return ResourceManager.GetString("MODULE_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not owner&apos;s course module .
        /// </summary>
        public static string MODULE_NOT_OF_USER {
            get {
                return ResourceManager.GetString("MODULE_NOT_OF_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module position must be greater or equal zero.
        /// </summary>
        public static string MODULE_POSITION_GREATHER_OR_EQUAL_ZERO {
            get {
                return ResourceManager.GetString("MODULE_POSITION_GREATHER_OR_EQUAL_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module postion is out of range.
        /// </summary>
        public static string MODULE_POSITION_OUT_RANGE {
            get {
                return ResourceManager.GetString("MODULE_POSITION_OUT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This course is already on order user.
        /// </summary>
        public static string ORDER_ITEM_EXISTS {
            get {
                return ResourceManager.GetString("ORDER_ITEM_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passing score must be less than 10.
        /// </summary>
        public static string PASSING_SCORE_LESS_THAN_TEN {
            get {
                return ResourceManager.GetString("PASSING_SCORE_LESS_THAN_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quiz doesn&apos;t exists.
        /// </summary>
        public static string QUIZ_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("QUIZ_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid rating type.
        /// </summary>
        public static string RATING_OUT_ENUM {
            get {
                return ResourceManager.GetString("RATING_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Review not exists.
        /// </summary>
        public static string REVIEW_NOT_EXISTS {
            get {
                return ResourceManager.GetString("REVIEW_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doesn&apos;t have acces for this review.
        /// </summary>
        public static string REVIEW_NOT_OF_USER {
            get {
                return ResourceManager.GetString("REVIEW_NOT_OF_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Teacher doesn&apos;t have courses yet.
        /// </summary>
        public static string TEACHER_DOESNT_HAVE_COURSES {
            get {
                return ResourceManager.GetString("TEACHER_DOESNT_HAVE_COURSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text field can&apos;t be null or empty.
        /// </summary>
        public static string TEXT_CANT_BE_NULL {
            get {
                return ResourceManager.GetString("TEXT_CANT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Text length must be less than 3000.
        /// </summary>
        public static string TEXT_LENGTH_MUST_BE_LESS_THAN_300 {
            get {
                return ResourceManager.GetString("TEXT_LENGTH_MUST_BE_LESS_THAN_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title must be equal or less than 250.
        /// </summary>
        public static string TITLE_EQUAL_OR_LESS_THAN_250 {
            get {
                return ResourceManager.GetString("TITLE_EQUAL_OR_LESS_THAN_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title cannot be null or empty.
        /// </summary>
        public static string TITLE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("TITLE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not have permission for access this content.
        /// </summary>
        public static string USER__NOT_HAVE_LESSON {
            get {
                return ResourceManager.GetString("USER__NOT_HAVE_LESSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must get course access for it.
        /// </summary>
        public static string USER_DOESNT_GOT_COURSE {
            get {
                return ResourceManager.GetString("USER_DOESNT_GOT_COURSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User infos doesn&apos;t exists.
        /// </summary>
        public static string USER_INFOS_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("USER_INFOS_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be logged for access this.
        /// </summary>
        public static string USER_NOT_LOGGED {
            get {
                return ResourceManager.GetString("USER_NOT_LOGGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video doesn&apos;t exists.
        /// </summary>
        public static string VIDEO_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("VIDEO_DOESNT_EXISTS", resourceCulture);
            }
        }
    }
}
