//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Course.Exception.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course description length must be less or equal 3000.
        /// </summary>
        internal static string COURSE_DESCRIPTION_3000_LENGTH {
            get {
                return ResourceManager.GetString("COURSE_DESCRIPTION_3000_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course doesn&apos;t exists.
        /// </summary>
        internal static string COURSE_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("COURSE_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course language must be within enum.
        /// </summary>
        internal static string COURSE_LANGUAGE_OUT_ENUM {
            get {
                return ResourceManager.GetString("COURSE_LANGUAGE_OUT_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The course must be of user.
        /// </summary>
        internal static string COURSE_NOT_OF_USER {
            get {
                return ResourceManager.GetString("COURSE_NOT_OF_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course description length must be less or equal 256.
        /// </summary>
        internal static string COURSE_TITLE_LENGTH_LESS_THAN_256 {
            get {
                return ResourceManager.GetString("COURSE_TITLE_LENGTH_LESS_THAN_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid image name.
        /// </summary>
        internal static string INAVLID_IMAGE_NAME {
            get {
                return ResourceManager.GetString("INAVLID_IMAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid course container.
        /// </summary>
        internal static string INVALID_COURSE_CONTAINER {
            get {
                return ResourceManager.GetString("INVALID_COURSE_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only format image is png and jpg.
        /// </summary>
        internal static string INVALID_FORMAT_IMAGE {
            get {
                return ResourceManager.GetString("INVALID_FORMAT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module doesn&apos;t exists.
        /// </summary>
        internal static string MODULE_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("MODULE_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not owner&apos;s course module .
        /// </summary>
        internal static string MODULE_NOT_OF_USER {
            get {
                return ResourceManager.GetString("MODULE_NOT_OF_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Module postion is out of range.
        /// </summary>
        internal static string MODULE_POSITION_OUT_RANGE {
            get {
                return ResourceManager.GetString("MODULE_POSITION_OUT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not have permission for access this content.
        /// </summary>
        internal static string USER__NOT_HAVE_LESSON {
            get {
                return ResourceManager.GetString("USER__NOT_HAVE_LESSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User infos doesn&apos;t exists.
        /// </summary>
        internal static string USER_INFOS_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("USER_INFOS_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video doesn&apos;t exists.
        /// </summary>
        internal static string VIDEO_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("VIDEO_DOESNT_EXISTS", resourceCulture);
            }
        }
    }
}
